"""add outfit model

Revision ID: 2f34f55fad63
Revises: 
Create Date: 2026-05-14 07:47:26.413823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f34f55fad63'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outfits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('outfit_name', sa.String(), nullable=False),
    sa.Column('outfit_description', sa.Text(), nullable=True),
    sa.Column('styling_tips', sa.Text(), nullable=True),
    sa.Column('color_story', sa.Text(), nullable=True),
    sa.Column('why_it_fits_you', sa.Text(), nullable=True),
    sa.Column('item_ids', sa.Text(), nullable=True),
    sa.Column('context_occasion', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outfits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outfits_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outfits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outfits_id'))

    op.drop_table('outfits')
    # ### end Alembic commands ###
